version: "3"
services:
  mariadb:
    build: ./requirements/mariadb
    container_name: "mariadb"
    image: "mariadb"
    volumes:
      - "db_data:/var/lib/mysql"
    expose:
      - "3306"
    env_file:
      - ".env"
    networks:
      - net
    restart: on-failure

  wordpress:
    build: ./requirements/wordpress
    container_name: "wordpress"
    image: "wordpress"
    networks:
      - net
    expose:
      - "9000"
    depends_on:
      - mariadb
    volumes:
      - "wordpress_data:/var/www/html/wordpress"
    env_file:
      - ".env"
    restart: on-failure

  nginx:
    build: ./requirements/nginx
    container_name: "nginx"
    image: "nginx"
    ports:
      - "433:433"
    volumes:
      - "wordpress_data:/var/www/html/wordpress"
    depends_on:
      - wordpress
    networks:
      - net
    expose:
      - "443"
    restart: on-failure

networks:
  net:
    name: net
    driver: bridge

volumes:
  db_data:
    driver: local
    name: db_data
    driver_opts:
      device: '/home/mseo/data/mysql'
      o: bind
      type: volume

  wordpress_data:
    driver: local
    name: wordpress_data
    driver_opts:
      device: '/home/mseo/data/wordpress'
      o: bind
      type: volume
