FROM	debian:buster

LABEL	MAINTAINER="mseo@student.42seoul.kr"

RUN		apt-get update && apt-get upgrade -y
RUN		apt-get install -y \
		MariaDB

# COPY	#파일 추가할 것을 써둬야함.

#CMD 	[ "executable" ]
# 컨테이너에서 실행할 명령을 입력